#!/usr/bin/php
<?php

define('DOCROOT', './www/');
define('ROOTPATH', './');
define('SYSPATH', './');
define('APPPATH', './application/');
define('STORAGE', './storage/');
define('CONFIG', APPPATH . 'common/config/');
define('ENVPATH', './');

require_once SYSPATH . 'vendor/autoload.php';
require_once SYSPATH . 'vendor/az/sys/src/autoload.php';
require_once SYSPATH . 'vendor/az/sys/src/library.php';
require_once CONFIG . 'bootstrap.php';

$container = (new \Sys\ContainerFactory('cli'))
    ->create(new \DI\ContainerBuilder());

$app = $container->get('\Sys\Console\App');
$app->run();
